"""empty message

Revision ID: 512330463b12
Revises: 6c492bf84906
Create Date: 2020-09-17 20:10:30.910365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512330463b12'
down_revision = '6c492bf84906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
