version: '3.7'

volumes:
  backend_db_data:

services:

  backend:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./backend
    command: uwsgi --ini /opt/app/uwsgi.ini
    depends_on:
      - backend_db
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 200M

  backend_db:
    image: postgres:12.4-alpine
    restart: unless-stopped
    volumes:
      - backend_db_data:/var/lib/postgresql/data
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
        reservations:
          cpus: '0.10'
          memory: 100M
