"""empty message

Revision ID: 77e0a79fc278
Revises: fde8e1961df7
Create Date: 2020-09-16 19:59:26.151803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e0a79fc278'
down_revision = 'fde8e1961df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'url')
    # ### end Alembic commands ###
