"""empty message

Revision ID: 0d78d2b4a911
Revises: 89d6401b7f62
Create Date: 2020-09-16 20:00:34.078147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d78d2b4a911'
down_revision = '89d6401b7f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('done', sa.Boolean(), nullable=True))
    op.add_column('resources', sa.Column('keywords_found', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('resources', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resources', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_column('resources', 'task_id')
    op.drop_column('resources', 'keywords_found')
    op.drop_column('resources', 'done')
    # ### end Alembic commands ###
