"""empty message

Revision ID: 6c492bf84906
Revises: 0d78d2b4a911
Create Date: 2020-09-17 03:52:37.175550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c492bf84906'
down_revision = '0d78d2b4a911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'created_date')
    # ### end Alembic commands ###
