"""empty message

Revision ID: a3d04b1d306b
Revises: 512330463b12
Create Date: 2020-09-17 20:21:28.040879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d04b1d306b'
down_revision = '512330463b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_items', sa.Column('resource_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource_items', 'resources', ['resource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource_items', type_='foreignkey')
    op.drop_column('resource_items', 'resource_id')
    # ### end Alembic commands ###
